package Math_Problems;

/*

    Description:
      Following program extracts all non-zero digits from an integer, concatenates
        them into a new number, computes their sum, and returns the product of both...

    Problem Statement:
      -> Given a positive integer n...
      -> Extract all non-zero digits from n while ignoring zeros...
      -> Concatenate the non-zero digits in their original left-to-right order...
      -> Compute the sum of all non-zero digits...
      -> Return concatenated_number × digit_sum...

    Key Insight:
      -> Digit extraction using % 10 yields digits right-to-left...
      -> A multiplier variable tracks positional value for correct concatenation...
      -> Each extracted non-zero digit is placed at the correct position in number...
      -> Sum accumulates in parallel during the same single pass...
      -> Both number and sum are computed together without separate passes...

    Example:
      -> n = 1020:
           Extract digits right-to-left: 0 (skip), 2 (keep), 0 (skip), 1 (keep)...
           Non-zero digits in order: 1, 2...
           Concatenated number = 12...
           Sum = 1 + 2 = 3...
           Result = 12 × 3 = 36...
      -> n = 505:
           Non-zero digits: 5, 5...
           Concatenated = 55, Sum = 10...
           Result = 55 × 10 = 550...
      -> n = 9999:
           All digits non-zero: 9, 9, 9, 9...
           Concatenated = 9999, Sum = 36...
           Result = 9999 × 36 = 359964...

    Concatenation Logic:
      -> Digits are extracted right-to-left (LSB first) via n % 10...
      -> A multiplier starts at 1 and increases by 10× for each non-zero digit kept...
      -> Each new non-zero digit is placed at the current multiplier position:
           number = remainder * multiplier + number...
      -> This builds the number from right to left, preserving original digit order...
      -> Zeros are completely skipped — neither added to sum nor placed in number...

    Step-by-Step Trace (n = 102030):
      -> n=102030: remainder=0, zero → skip, n=10203...
      -> n=10203:  remainder=3, non-zero → sum=3, number=3×1+0=3, multiplier=10, n=1020...
      -> n=1020:   remainder=0, zero → skip, n=102...
      -> n=102:    remainder=2, non-zero → sum=5, number=2×10+3=23, multiplier=100, n=10...
      -> n=10:     remainder=0, zero → skip, n=1...
      -> n=1:      remainder=1, non-zero → sum=6, number=1×100+23=123, multiplier=1000, n=0...
      -> Loop ends: number=123, sum=6...
      -> Result = 123 × 6 = 738...

    Why long Instead of int?
      -> Concatenating digits of large numbers can exceed int range (> 2^31 - 1)...
      -> Product of concatenated number and sum can be very large...
      -> long provides up to 64-bit range (≈ 9.2 × 10^18) for safety...
      -> Cast remainder * multiplier to long before addition to avoid overflow...

    Why multiplier Only Increments for Non-Zero Digits:
      -> multiplier tracks the place value of the next non-zero digit in result...
      -> Zero digits are skipped entirely → place value must not advance for them...
      -> Advancing multiplier for zeros would leave gaps in the concatenated number...
      -> Example: n=1020 → skipping zeros ensures 1 and 2 become 12, not 1_2_...

    Edge Cases:
      -> Number with all zeros except one digit (e.g., 1000) → number=1, sum=1 → result=1...
      -> Number with no zeros (e.g., 1234) → all digits kept → result = 1234 × 10...
      -> Single digit non-zero → number = that digit, sum = that digit → result = digit²...
      -> Alternating zeros (e.g., 102030) → only non-zero digits extracted in order...

    Time and Space Complexity:
      -> Time:  O(log n) — one pass through all digits of n (log₁₀(n) iterations)...
      -> Space: O(1) — only fixed number of integer variables used...

    Applications:
      -> Custom digit transformation problems in competitive programming...
      -> Number theory puzzles involving selective digit extraction...
      -> Encoding schemes that compress integers by removing placeholder zeros...
      -> Mathematical property investigations on digit subsets of integers...

*/

public class Concatenate_Non_Zero_Digits_And_Multiply_By_Sum {

    private static long sumAndMultiply(int n) {

        long sum = 0;
        long number = 0;
        int multiplier = 1;

        while (n != 0) {
            int remainder = n % 10;

            if (remainder != 0) {
                sum += remainder;
                number = (long) remainder * multiplier + number;
                multiplier *= 10;
            }

            n /= 10;
        }

        return number * sum;
    }

    public static void main(String[] args) {
        
        System.out.println("╔══════════════════════════════════════════════════════════════╗");
        System.out.println("║   CONCATENATE NON-ZERO DIGITS AND MULTIPLY BY SUM            ║");
        System.out.println("║  Extract non-zero digits, concatenate, sum, then multiply    ║");
        System.out.println("╚══════════════════════════════════════════════════════════════╝\n");

        testCase(1234, "1234");
        testCase(1020, "12");
        testCase(100, "1");
        testCase(505, "55");
        testCase(9999, "9999");
        testCase(2468, "2468");
        testCase(1000, "1");
        testCase(102030, "123");

        System.out.println("╔══════════════════════════════════════════════════════════════╗");
        System.out.println("║  ALGORITHM: Extract non-zeros, concatenate, multiply by sum  ║");
        System.out.println("║  Example: 1020                                               ║");
        System.out.println("║    Non-zero digits: 1, 2                                     ║");
        System.out.println("║    Concatenated: 12                                          ║");
        System.out.println("║    Sum: 1 + 2 = 3                                            ║");
        System.out.println("║    Result: 12 × 3 = 36                                       ║");
        System.out.println("║  Time: O(log n), Space: O(1)                                 ║");
        System.out.println("╚══════════════════════════════════════════════════════════════╝");
        
    }

    private static void testCase(int n, String digits) {

        long result = sumAndMultiply(n);
        String[] parts = digits.split("");

        long sum = 0;
        for (String d : parts) {
            sum += Long.parseLong(d);
        }

        long concatenated = Long.parseLong(digits);
        long expected = concatenated * sum;

        System.out.println("n = " + n + "\ndigits : " + digits + "\nsum : " + sum +
            "\nconcat : " + concatenated + "\nresult : " + result +
            (result == expected ? " ✓" : " ✗"));

        System.out.println("\n");

    }

}
